name: 自動發佈

on:
  push:
    branches: [main]
    paths: # 暫時只發佈 Lite 版本
      - "LiteVersion.yaml"
      # - "Pack/**"
      # - "APPID/**"
      # - "RePKG/**"
      # - "DepotDownloaderMod/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_release:
    name: 編譯與發佈
    runs-on: windows-latest

    steps:
      - name: 取得倉庫代碼
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: 安裝並驗證 yq 工具
        uses: mikefarah/yq@v4
        with:
          cmd: yq --version

      - name: 初始化依賴並準備發佈資訊
        id: version
        run: |
          $tag = $(yq e '.tag' LiteVersion.yaml).Trim('"')
          $version = $(yq e '.version' LiteVersion.yaml).Trim('"')
          yq -r e '.description' LiteVersion.yaml | Out-File -FilePath "Release_notes.md" -Encoding utf8

          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "TAG=$tag" >> $env:GITHUB_OUTPUT

      - name: 設定 Python 環境
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"
          cache: "pip"

      - name: 安裝 Python 依賴
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r Pack/LiteRequirements.txt

      - name: PyInstaller 編譯
        id: build
        run: |
          pyinstaller Pack/LitePack.spec --upx-dir Pack
          $exe_name = (Get-ChildItem -Path "dist" -Filter "*.exe").Name
          echo "EXE_NAME=$exe_name" >> $env:GITHUB_OUTPUT

      - name: 將 EXE 壓縮為 ZIP
        id: archive
        run: |
          $zip_name = "WallpaperEngineDownloader_Lite_${{ steps.version.outputs.VERSION }}.zip"
          Compress-Archive -Path "dist/${{ steps.build.outputs.EXE_NAME }}" -DestinationPath $zip_name
          echo "ZIP_NAME=$zip_name" >> $env:GITHUB_OUTPUT

      - name: 建立或更新 Release 並上傳 ZIP
        uses: softprops/action-gh-release@v2
        with:
          body_path: Release_notes.md
          files: ${{ steps.archive.outputs.ZIP_NAME }}
          name: Release ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ steps.version.outputs.TAG }}
