name: 自動發佈

on:
  push:
    branches: [main]
    paths: # 暫時只發佈 Lite 版本
      - "LiteVersion.yaml"
      # - "Pack/**"
      # - "APPID/**"
      # - "RePKG/**"
      # - "DepotDownloaderMod/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_release:
    name: 編譯與發佈
    runs-on: windows-latest

    steps:
      - name: 取得倉庫代碼
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: 設定 yq 環境
        uses: vegardit/gha-setup-yq@v1

      - name: 取得發佈資訊
        id: version
        run: |
          $tag = yq -r '.tag' LiteVersion.yaml
          $version = yq -r '.version' LiteVersion.yaml
          $description = yq -r '.description' LiteVersion.yaml

          $description | Out-File -FilePath "Release_notes.md" -Encoding utf8

          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "TAG=$tag" >> $env:GITHUB_OUTPUT

      - name: 設定 uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true

      - name: 建立 Python 環境
        run: uv venv --python 3.14

      - name: 安裝 Python 依賴
        run: uv pip install -r Pack/LiteRequirements.txt

      - name: PyInstaller 編譯
        id: build
        run: |
          .venv\Scripts\pyinstaller.exe Pack/LitePack.spec --upx-dir Pack --clean
          $exe_name = (Get-ChildItem -Path "dist" -Filter "*.exe").Name
          echo "EXE_NAME=$exe_name" >> $env:GITHUB_OUTPUT

      - name: 準備並壓縮發佈檔案
        id: archive
        run: |
          $release_dir = "WallpaperEngineDownloader"
          $zip_name = "WallpaperEngineDownloader_${{ steps.version.outputs.VERSION }}_Lite.zip"

          New-Item -ItemType Directory -Name $release_dir

          Copy-Item -Path "dist/${{ steps.build.outputs.EXE_NAME }}" -Destination $release_dir
          Copy-Item -Path "DepotDownloaderMod" -Destination $release_dir -Recurse
          Copy-Item -Path "Icon" -Destination $release_dir -Recurse

          Compress-Archive -Path $release_dir -DestinationPath $zip_name

          echo "ZIP_NAME=$zip_name" >> $env:GITHUB_OUTPUT

      - name: 建立或更新 Release
        uses: softprops/action-gh-release@v3
        with:
          body_path: Release_notes.md
          files: ${{ steps.archive.outputs.ZIP_NAME }}
          name: Release ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ steps.version.outputs.TAG }}
